FROM nvidia/cuda:12.6.0-cudnn-devel-ubuntu22.04

# Install language
RUN apt-get update && apt-get install -y --no-install-recommends \
  locales \
  && locale-gen en_US.UTF-8 \
  && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
  && rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8

# Install timezone
RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y --no-install-recommends tzdata \
  && dpkg-reconfigure --frontend noninteractive tzdata \
  && rm -rf /var/lib/apt/lists/*

# Install common programs
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gnupg2 \
    sudo \
    lsb-release \
    software-properties-common \
    wget \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install ROS2
RUN sudo add-apt-repository universe \
  && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null \
  && apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-ros-base \
    python3-argcomplete \
    ros-humble-rmw-cyclonedds-cpp \
    ros-dev-tools \
    python3-colcon-clean \
    ros-humble-ament-* \
  && rm -rf /var/lib/apt/lists/*
# cv_bridge
RUN apt-get update && apt-get install -y --no-install-recommends \
    libboost-all-dev \
    libboost-python-dev \
    python3-dev \
  && rm -rf /var/lib/apt/lists/*



# bloom and fake
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-bloom \
    fakeroot \
    debhelper \
    dh-python \
  && rm -rf /var/lib/apt/lists/*

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Check if "ubuntu" user exists, delete it if it does, then create the desired user
RUN if getent passwd ubuntu > /dev/null 2>&1; then \
        userdel -r ubuntu && \
        echo "Deleted existing ubuntu user"; \
    fi && \
    groupadd --gid $USER_GID $USERNAME && \
    useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    echo "Created new user $USERNAME"

# Add sudo support for the non-root user
RUN apt-get update && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  && rm -rf /var/lib/apt/lists/*

# Install OpenCV


# Copy all OpenCV debs for both architectures to /tmp
COPY opencv_debs/OpenCV*.deb /tmp/

RUN ARCH=$(uname -m) && \
    apt update && \
    if [ "$ARCH" = "aarch64" ]; then \
        apt install -y /tmp/OpenCV-*-aarch64-*.deb; \
    elif [ "$ARCH" = "x86_64" ]; then \
        apt install -y /tmp/OpenCV-*-x86_64-*.deb; \
    else \
        echo "Unsupported architecture: $ARCH"; exit 1; \
    fi && \
    rm -rf /tmp/OpenCV*.deb

RUN apt-get update && apt-get install -y --no-install-recommends \
    devscripts \
  && rm -rf /var/lib/apt/lists/*